name: Update

on:
  push:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  update:
    name: Update map data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        run: git submodule update --init --recursive --remote

      - name: Push results
        run: |
          git config --global user.email "bot@gh.com"
          git config --global user.name "GitBot"
          git add -u
          git commit -am "Maps updated"
          git push
